### ISSUE TITLE
aiohttp throws "RuntimeError: Timeout context manager should be used inside a task" on linked room creation

### ISSUE THREAD

**Issue by networkjanitor** [Cadair/python-appservice-framework#12]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/matrix_discord_bridge-0.0.1.dev0-py3.6.egg/appservice/app.py", line 179, in on_message
    return await self.handle_discord_message(message)
  File "/usr/local/lib/python3.6/site-packages/matrix_discord_bridge-0.0.1.dev0-py3.6.egg/appservice/app.py", line 109, in handle_discord_message
    room = await self.create_new_room(auth_user, service_roomid)
  File "/usr/local/lib/python3.6/site-packages/matrix_discord_bridge-0.0.1.dev0-py3.6.egg/appservice/app.py", line 154, in create_new_room
    room = await self.apps.create_linked_room(auth_user, service_roomid, matrix_roomname=channel_name)
  File "/usr/local/lib/python3.6/site-packages/appservice_framework-0.1.0-py3.6.egg/appservice_framework/appservice.py", line 879, in create_linked_room
    query_params={'auth_token': self.api.token})
  File "/usr/local/lib/python3.6/site-packages/appservice_framework-0.1.0-py3.6.egg/appservice_framework/matrix_api.py", line 74, in _send
    async with request as response:
  File "/usr/local/lib/python3.6/site-packages/aiohttp-3.3.2-py3.6.egg/aiohttp/client.py", line 843, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp-3.3.2-py3.6.egg/aiohttp/client.py", line 317, in _request
    with timer:
  File "/usr/local/lib/python3.6/site-packages/aiohttp-3.3.2-py3.6.egg/aiohttp/helpers.py", line 662, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task
```

The AppService get initialised in a similar fashion to the way it is done in the hangoutsas:

```
    def run(self):
        self.apps = AppService(
            matrix_server=self.args[CPNs.MX_HS],
            server_domain=self.args[CPNs.MX_HS_DOMAIN],
            access_token=self.args[CPNs.MX_AS_TOKEN],
            user_namespace=self.args[CPNs.AS_USER_NS],
            sender_localpart=self.args[CPNs.AS_SENDER_LOCAL],
            room_namespace=self.args[CPNs.AS_ROOM_NS],
            database_url=self.args[CPNs.DB_URI],
            loop=self.loop, # in class __init__: self.loop = loop or asyncio.get_event_loop()
            invite_only_rooms=self.args[CPNs.AS_INVITE_ONLY_ROOMS]
        )

        # service_connect handler and user creation snipped 

        with self.apps.run() as run_forever:
            run_forever()
```

Any idea why this is happening ? Any idea on how to troubleshoot it or information you would need to fix/give help ?

**Comment by networkjanitor** [comment]
Issue has been resolved, after enabling `loop.set_debug(True)` the error changed to `RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one`. Which made a lot more sense and allowed me to fix my issue by calling apps.create_linked_room threadsafe:

```
room_future = asyncio.run_coroutine_threadsafe(
    self.apps.create_linked_room(auth_user, service_roomid, matrix_roomname=channel_name),
    self.loop
)
room = room_future.result()

```
