### ISSUE TITLE
Reuse existing rooms with AS alias for prevent M_FORBIDDEN events

### ISSUE THREAD

**Issue by MurzNN** [Cadair/python-appservice-framework#3]
For post new messages to AS-managed rooms, AS user must be a member (maybe with admin permissions?) of all rooms.

But sometimes it can not be a member of room:
- If this room was already exists before AS is added to server (eq if user use other AS with same `sender_localpart` and replace it to new AS).
- If user kick manually this user from room.

In this situations now AS shows the error:
```
matrix_client.errors.MatrixRequestError: 403: {"errcode":"M_FORBIDDEN","error":"User @hangouts:homeserver.org not in room !uJsAiCcPjyKuXTJHTo:homeserver.org (None)"}
```
And when user try to manually invite `@hangouts` user to room - we got another error:
```
appservice_framework ERROR    Membership event received, handling is not yet implemented.
```

For solve this problems, we must implement managing membership events (for accept manual invites of AS user to rooms), and force joining AS user to managed rooms, if it missed in room member list.

**Comment by MurzNN** [comment]
You can emulate this situation via manually kicking AS user from current room, created via AS, and send new message to this room via AS. You must got "M_FORBIDDEN" and no way to join AS user to this room again - if you invite it manually, it don't accept this invite and will stay in invited state instead of member.

**Comment by MurzNN** [comment]
Seems it works normally even if AS user is leave room, I can't reproduce this via kicking AS user.
So the problem is only with reuse old rooms (created from other AS). Maybe the problem is that those rooms are missed in AS internal database (sqlite)?

**Comment by MurzNN** [comment]
Yes, seems the problem is in AS internal database (sqlite), steps to reproduce:
1. Start AS (with sqlite db), send message from external hangouts user. AS will create new Matrix room and post the incoming message.
2. Stop AS, remove sqlite database file, start AS again.
3. Send next message from same external hangouts user.
4. You will not receive this message with error like:
```
2018-01-18 19:01:23,478 hangouts_appservice  DEBUG    Received message in hangouts room: UgwovSuHBIIlwXcF8dt4AaABAagBmLmgDA from user 100199384108425402865
2018-01-18 19:01:23,733 appservice_framework DEBUG    Creating room hangouts_UgwovSuHBIIlwXcF8dt4AaABAagBmLmgDA
Task exception was never retrieved
future: <Task finished coro=<Client.connect() done, defined at /usr/local/lib/python3.6/dist-packages/hangups/client.py:116> exception=MatrixRequestError('403: {"errcode":"M_FORBIDDEN","error":"@hangouts:h.ru not in room !KKIdiRIVhBBEsgFscZ:homeserver.ru."}',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hangups/client.py", line 140, in connect
    yield from self._listen_future
  File "/usr/local/lib/python3.6/dist-packages/hangups/channel.py", line 211, in listen
    yield from self._longpoll_request()
  File "/usr/local/lib/python3.6/dist-packages/hangups/channel.py", line 321, in _longpoll_request
    yield from self._on_push_data(chunk)
  File "/usr/local/lib/python3.6/dist-packages/hangups/channel.py", line 358, in _on_push_data
    yield from self.on_receive_array.fire(data_array)
  File "/usr/local/lib/python3.6/dist-packages/hangups/event.py", line 60, in fire
    yield from gen
  File "/usr/local/lib/python3.6/dist-packages/hangups/client.py", line 383, in _on_receive_array
    yield from self.on_state_update.fire(state_update)
  File "/usr/local/lib/python3.6/dist-packages/hangups/event.py", line 60, in fire
    yield from gen
  File "/usr/local/lib/python3.6/dist-packages/hangups/conversation.py", line 845, in _on_state_update
    state_update.event_notification.event
  File "/usr/local/lib/python3.6/dist-packages/hangups/conversation.py", line 898, in _on_event
    yield from self.on_event.fire(conv_event)
  File "/usr/local/lib/python3.6/dist-packages/hangups/event.py", line 60, in fire
    yield from gen
  File "/usr/local/lib/python3.6/dist-packages/matrix_appservice_hangouts/hangouts_client.py", line 151, in on_event
    await self.recieve_event_handler(self, conv, user, conv_event)
  File "/usr/local/lib/python3.6/dist-packages/matrix_appservice_hangouts/__main__.py", line 114, in handle_hangouts_message
    room = await create_new_room(apps, client, auth_user, service_roomid)
  File "/usr/local/lib/python3.6/dist-packages/matrix_appservice_hangouts/__main__.py", line 66, in create_new_room
    matrix_roomname=convname)
  File "/usr/local/lib/python3.6/dist-packages/appservice_framework/appservice.py", line 886, in create_linked_room
    await self._invite_user(roomid, auth_user.matrixid)
  File "/usr/local/lib/python3.6/dist-packages/appservice_framework/appservice.py", line 283, in _invite_user
    raise e
  File "/usr/local/lib/python3.6/dist-packages/appservice_framework/appservice.py", line 279, in _invite_user
    query_params={'auth_token': self.api.token})
  File "/usr/local/lib/python3.6/dist-packages/appservice_framework/matrix_api.py", line 77, in _send
    code=response.status, content=await response.text())
matrix_client.errors.MatrixRequestError: 403: {"errcode":"M_FORBIDDEN","error":"@hangouts:homeserver.ru not in room !KKIdiRIVhBBEsgFscZ:homeserver.ru."}
```

**Comment by MurzNN** [comment]
As I understand, AS on receive `M_FORBIDDEN` error need to check if room with needed alias like `#hangouts_UXwovSuHBIIlwGXXXXt4AaABAagBmLmgDA:homeserver.org` exists in Matrix server, and if exists, but missed in AS sqlite database - insert row to table with this room id like
```
INSERT INTO "room" VALUES(1,'bridged','!KKIdiRIXXXXEsSFscZ:homeserver.org','#hangouts_UXwovSuHBIIlwGXXXXt4AaABAagBmLmgDA:homeserver.org',serviceid,matrixid);
INSERT INTO "linked_room" VALUES(1,'UXwovSuHBIIlwGXXXXt4AaABAagBmLmgDA',frontier_userid);
```
Also we need to check if user is a member of this group, and re-join he if missed, or remove alias from old room and create new room. Eg user leave the room, created by AS, and will not see new messages that AS will post in it.

**Comment by Cadair** [comment]
After discussing this in chat, it's not possible because of the ACLs on rooms (for very good reasons). 

The "solution" to this is to enable the bridge to be invited to rooms, which is a component of the single puppet bridge workflow.
